---
require: 'rubocop-rspec'

AllCops:
  Exclude:
    - 'bin/*'
    - 'pkg/**/*'
    - 'spec/fixtures/**/*'
    - 'vendor/**/*'

Layout/FirstArrayElementLineBreak:
  Enabled: true

Layout/FirstHashElementLineBreak:
  Enabled: true

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/FirstMethodParameterLineBreak:
  Enabled: true

Lint/MissingCopEnableDirective:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  # TODO: Reduce this value.
  Max: 127

Naming/HeredocDelimiterNaming:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/acceptance/**/*'
    - 'spec/classes/**/*'

RSpec/ExampleLength:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/SharedExamples:
  Enabled: false

Style/CollectionMethods:
  Enabled: true

Style/DocumentationMethod:
  Enabled: true

Style/FormatStringToken:
  Enabled: false

Style/ImplicitRuntimeError:
  Enabled: true

Style/InlineComment:
  Enabled: true

Style/MethodCallWithArgsParentheses:
  Enabled: true
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
  IgnoredMethods:
    - 'include'
    - 'require'
    - 'require_relative'

    # RSpec
    - 'context'
    - 'describe'
    - 'include_context'
    - 'it'
    - 'not_to'
    - 'to'

Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/NumericLiterals:
  Enabled: false

Style/OptionHash:
  Enabled: true

Style/StringMethods:
  Enabled: true

Style/SymbolArray:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: 'comma'

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: 'comma'

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: 'comma'
